CREATE DATABASE IF NOT EXISTS phone_service;
USE phone_service;

CREATE TABLE IF NOT EXISTS registrations (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100),
  email VARCHAR(150),
  phone CHAR(6) UNIQUE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
